#!/bin/sh
set -eux
SHIP=$1; shift
PIER="/home/$SHIP/$SHIP"

if [ 0 -ne "$(id -u)" ]; then
  echo must run as root >&2
  exit 1
fi

if systemctl is-active --quiet "urbit@$SHIP"; then
  cleanup() {
    systemctl start "urbit@$SHIP"
  }
  systemctl stop "urbit@$SHIP"
  trap cleanup EXIT
fi

sudo -u "$SHIP" /usr/bin/env "PIER=$PIER" /bin/sh -eux <<'EOF'
cleanup() {
  if [ -d "$PIER/.urb/bhk" ]; then
    rm -rf "$PIER/.urb/ahk"
  elif [ -d "$PIER/.urb/ahk" ]; then
    mv "$PIER/.urb/ahk" "$PIER/.urb/bhk"
  else
    cp --reflink=auto "$PIER/.urb/chk" "$PIER/.urb/bhk"
  fi
}

cleanup
trap cleanup EXIT
mv "$PIER/.urb/bhk" "$PIER/.urb/ahk"
"$PIER/.run" meld
EOF
